name: dfmdet
channels:
  - conda-forge
platforms:
  - osx-arm64
  - linux-64
  - osx-64
dependencies:
  # run
  - python=3.11
  - esutil
  - galsim
  - joblib
  - ngmix
  - numba
  - numpy

  # install
  - pip
  - setuptools
  - setuptools_scm>=7

  # dev
  - pytest<8.1.0
  - pytest-xdist
  - pytest-cov
  - python-build
  - codecov
  - pre-commit
